### ISSUE TITLE
Connection names on ulauncher

### ISSUE THREAD

**Issue by luisg0nc** [noam09/ulauncher-remmina#1]
## Expected Behavior

Remmina Profiles names show up on uLauncher.

## Actual Behavior

File name hashes of the profiles show up on uLauncher.

![problem-ulauncher](https://user-images.githubusercontent.com/24317697/50151707-8e3bcd80-02b9-11e9-8319-0d454cfc9a20.png)

## Steps to Reproduce the Problem

  1. Install Remmina
  2. Setup uLauncher and ulauncher-remmina
  3. Use extension 

## Specifications

  - Version:  ulauncher-remmina v0.0.2
  - Platform: Manjaro Arch Linux 18.0.0

**Comment by noam09** [comment]
Thanks for posting this.

I hope to have a fix by the end of the day, as soon as I have a few minutes of free time. :)

**Comment by luisg0nc** [comment]
Hey I fixed it! :smiley: 
See my pull request #2

**Comment by noam09** [comment]
Awesome! Thank you.
