### ISSUE TITLE
[BUG] Error while initial save of extension

### ISSUE THREAD

**Issue by Avinashachu007** [noam09/ulauncher-remmina#11]
### Describe the bug

I installed the extension by copy paste the github url mentioned in the extension page. I clicked save, an alert dialog show "an unexpected error occured"

### Environment

**Ulauncher version**: 2.10
**Linux distro**: Linux Mint 20.2 Uma
**Desktop environment**: Cinnamon

### Logs
Message: 'com.github.noam09.ulauncher-remmina'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.noam09.ulauncher-remmina'

```

**Comment by noam09** [comment]
Hey @Avinashachu007, in what directory are your Remmina profiles saved?

Also, did you use Snap/Flatpak for the Ulauncher or extension or Remmina installation? (https://github.com/noam09/ulauncher-remmina/issues/9#issuecomment-821767508)

**Comment by scan09** [comment]
same problem.
Archlinux - Gnome 40 - Ulauncher 5.11

**Comment by mateusz-gladczak** [comment]
Same problem here, Mint 20.02. Extensions crashes even if i add location to remmina profiles dir manually (which is ~/.var/app/org.remmina.Remmina/data/remmina/ ) in my case

**Comment by noam09** [comment]
Hey @scan09 and @mateusz-gladczak, did you use Snap/Flatpak for the Ulauncher or extension or Remmina installation?

**Comment by noam09** [comment]
Please open a new issue if needed.
