### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by bernoussama** [noam09/ulauncher-remmina#12]
### Describe the bug

cant install the extension

### Steps to reproduce

1. paste the link to ulauncher
2. get error

### Current behavior
```
There's an error in versions.json:
Commit/branch "master" does not exist or could not be retrieved.
A clear and concise description of the current behavior.
```

### Expected behavior

extension installed
### Environment

**Ulauncher version**: v5.15.7
**Linux distro**: popos 22.04
**Desktop environment**:  gnome 42

### Screenshots

![image](https://github.com/noam09/ulauncher-remmina/assets/96293508/7d7b8788-f4d1-4b2f-a18b-17b2928704d2)

**Comment by noam09** [comment]
Please open a new issue if needed.
