### ISSUE TITLE
Hangup

### ISSUE THREAD

**Issue by antonio-petricca** [noam09/ulauncher-remmina#5]
Hi, I have just installed it, and when I try to use it, it hangs on "Loading...".

Thank you so much!
Antonio

> com.github.noam09.ulauncher-remmina | 2019-08-19 11:18:43,211 | DEBUG | __main__: on_event() | Remmina profiles path: /home/antonio/.remmina
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
>     self.extension.trigger_event(event)
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
>     action = listener.on_event(event, self)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 99, in on_event
>     profiles_list = extension.list_profiles(term)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 72, in list_profiles
>     title, desc, proto = profile_details(p)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 191, in profile_details
>     server=server)

**Comment by noam09** [comment]
Hi @antonio-petricca, are there definitely profile files in `~/.remmina`? Have you tried restarting `ulauncher` since installing the extension? It's hard to tell from the log entry what exactly is causing the issue. Maybe a couple lines before or after the log can shed some more light on it?

**Comment by antonio-petricca** [comment]
Hi, I am running the version 5.3.0-beta1 .

My profile folder is `/home/antonio/.remmina` and I have restarted it several times.

Here is the complete log:

> 2019-08-19 12:27:52,092 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.noam09.ulauncher-remmina"
> DEBUG:ulauncher.api.client.Client:Incoming event KeywordQueryEvent
> com.github.noam09.ulauncher-remmina | 2019-08-19 12:27:52,095 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
> DEBUG:__main__:Remmina profiles path: /home/antonio/.remmina
> com.github.noam09.ulauncher-remmina | 2019-08-19 12:27:52,096 | DEBUG | __main__: on_event() | Remmina profiles path: /home/antonio/.remmina
> 2019-08-19 12:27:52,295 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
>     self.extension.trigger_event(event)
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
>     action = listener.on_event(event, self)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 99, in on_event
>     profiles_list = extension.list_profiles(term)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 72, in list_profiles
>     title, desc, proto = profile_details(p)
>   File "/home/antonio/.cache/ulauncher_cache/extensions/com.github.noam09.ulauncher-remmina/main.py", line 191, in profile_details
>     server=server)
> UnboundLocalError: local variable 'server' referenced before assignment
> 

Thank you again!

**Comment by noam09** [comment]
Please try updating again now.

**Comment by antonio-petricca** [comment]
It works!!!

Thank you so much!
