### ISSUE TITLE
[BUG] Can't launch if "&" in name

### ISSUE THREAD

**Issue by mauro-miatello** [noam09/ulauncher-remmina#8]
### Describe the bug

if the connection name contains "&" launcher can't run it

### Steps to reproduce

create a remote connection with "&" in name

### Current behavior

sometimes nothing happens, sometimes a popup appears with an error

### Expected behavior

Run the connection

### Environment

**Ulauncher version**: 5.9
**Linux distro**: Mint 20
**Desktop environment**: Cinnamon

**Comment by noam09** [comment]
Hey @mauro-miatello, can you please check if the latest version fixes the issue?

**Comment by mauro-miatello** [comment]
@noam09 yes! it works thanks!
but when I look for a host, I can't see the hostname, I don't know if it depends from & or spaces in the name or something other
![image](https://user-images.githubusercontent.com/11910225/111269954-88b3c600-862f-11eb-9f38-91270d12ecb2.png)

**Comment by noam09** [comment]
Glad to hear it works. Can you give an example of a profile name and group name which don't seem to work well?

Using the following profiles, here is what I see in Ulauncher:

![1](https://user-images.githubusercontent.com/564674/112480171-6b44d180-8d7e-11eb-8b24-69517e4068d9.png)

![2](https://user-images.githubusercontent.com/564674/112480183-6ed85880-8d7e-11eb-82c9-275a5a41df60.png)

**Comment by mauro-miatello** [comment]
I've just tried and everything seems working fine, thanks
